services:
  app:
    build:
      context: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - mongo_datos

  mongo_datos:
    image: mongo:4.4
    container_name: mongo_db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: